### ISSUE TITLE
BUG: Freezes if left until the red debug LED lights up in the top left

### ISSUE THREAD

**Issue by Gadgetoid** [Gadgetoid/galactic-bluetooth-audio#5]
1. Connect your phone
2. Play some music
3. Pause
4. Leave it for a moment
5. When FFT vanishes and the red LED lights in the top left try to play music again
6. BOOM?

**Comment by Gadgetoid** [comment]
This seems to mostly happen with iOS (my iPhone) and looking at serial, it floods the:

```
Error storing samples in SBC ring buffer!!!
```

Error.

**Comment by Gadgetoid** [comment]
Slightly more detailed log, albeit it's not very useful:

```
Connecting PIO I2S audio
Copying stereo to stereo at 44100 Hz
AVRCP Controller: Playback status changed PLAYING
AVRCP Controller: Playback status changed PLAYING
AVRCP Controller: Playback status changed PAUSED
AVRCP Controller: Playback status changed PAUSED
A2DP  Sink      : Stream paused
AVRCP Target    : Volume set to 18% (23)
A2DP  Sink      : Stream started
AVRCP Controller: Playback status changed PLAYING
AVRCP Controller: Playback status changed PLAYING
AVRCP Controller: Playback status changed PAUSED
AVRCP Controller: Playback status changed PAUSED
A2DP  Sink      : Stream paused
AVRCP Target    : Volume set to 18% (23)
A2DP  Sink      : Stream started
AVRCP Controller: Playback status changed PLAYING
AVRCP Controller: Playback status changed PLAYING
Error storing samples in SBC ring buffer!!!
Error storing samples in SBC ring buffer!!!
Error storing samples in SBC ring buffer!!!
Error storing samples in SBC ring buffer!!!
Error storing samples in SBC ring buffer!!!
Error storing samples in SBC ring buffer!!!
Error storing samples in SBC ring buffer!!!
Error storing samples in SBC ring buffer!!!
```

This error should (only?) trigger if the buffer is filling faster than the data can be consumed, so potentially the audio output is failing to init after it has been shut off by "A2DP Sink: Stream paused"

**Comment by Gadgetoid** [comment]
Bit more info on what functions are called when:
```
Connecting PIO I2S audio
Copying stereo to stereo at 44100 Hz
AVRCP Controller: Playback status changed PLAYING
AVRCP Controller: Playback status changed PLAYING
btstack_audio_pico_sink_start_stream
AVRCP Controller: Playback status changed PAUSED
AVRCP Controller: Playback status changed PAUSED
A2DP  Sink      : Stream paused
btstack_audio_pico_sink_stop_stream
AVRCP Target    : Volume set to 18% (23)
A2DP  Sink      : Stream started
AVRCP Controller: Playback status changed PLAYING
AVRCP Controller: Playback status changed PLAYING
btstack_audio_pico_sink_start_stream
AVRCP Controller: Playback status changed PAUSED
AVRCP Controller: Playback status changed PAUSED
A2DP  Sink      : Stream paused
btstack_audio_pico_sink_stop_stream
AVRCP Target    : Volume set to 18% (23)
A2DP  Sink      : Stream started
AVRCP Controller: Playback status changed PLAYING
AVRCP Controller: Playback status changed PLAYING
btstack_audio_pico_sink_start_stream
Error storing samples in SBC ring buffer!!!
Error storing samples in SBC ring buffer!!!
Error storing samples in SBC ring buffer!!!
```

**Comment by Gadgetoid** [comment]
I can remove the FFT and display code altogether and this bug still triggers, I'd bet it does the same on the vanilla example.

**Comment by Gadgetoid** [comment]
@kilograham @mringwal I’m a little out of my depth here, but I think this bug is in the regular a2dp sink example on the Pico W, do you have any off the cuff insight? Thanks.

**Comment by mringwal** [comment]
Hi. Please try this PR and let me know
https://github.com/raspberrypi/pico-extras/pull/58
(Looks like I never created a PR for this. It lets A2DP Sink Demo work after the first pause).

**Comment by Gadgetoid** [comment]
Looks like that's fixed it. Thank you!

Now I just have to bug engineering to make me a better speaker :laughing: 

Shout if you want some hardware (Galactic / Cosmic Unicorn) to play with this on.

**Comment by kilograham** [comment]
shout ;-)

**Comment by mringwal** [comment]
If @kilograham gets one, I'd also like one:)

Here's a futuristic idea: it looks like both iOS and Android support Cover Art since a bit (they didn't three years) ago, now, you've got a nice RGB display although it's a bit rectangular...

BTstack doesn't support Cover Art yet, but we plan to have it by summer.

**Comment by Gadgetoid** [comment]
Bung me an email with your particulars!

**Comment by Gadgetoid** [comment]
> Here's a futuristic idea: it looks like both iOS and Android support Cover Art since a bit (they didn't three years) ago, now, you've got a nice RGB display although it's a bit rectangular...

Cosmic is 32x32 pixels so album art could work - https://fosstodon.org/@gadgetoid/109933594917821802

Any idea off the top of your head what formats it would be expected in, or if that's controllable?  You're right, Lo-Fi album art could be really cool.

**Comment by mringwal** [comment]
Not top of my head, but I checked. It's mandatory to provide a 200x200 pixel thumbnail as JPEG. Other than that, the client can ask for a format/size/... and the server may or may not provide it. I'd assume that iOS/Android probably can scale the image and provide it as JPEG and PNG as a minimum. For your project, the 200x200 JPEG Thumbnail looks like the obvious choice. 

Btw. audio over a2dp is encoded as SBC, which dynamically distributes the available bits on a number of subbands - it's documented in Appendix B of the A2DP Specification. I guess, if you really really want to reduce computation, you could try to access these / the spectrum before it is even converted back to PCM... (just if you're really really bored or interested in maths).
